/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_istyle_document_convert_SPDocumentConvert */

#ifndef _Included_com_istyle_document_convert_SPDocumentConvert
#define _Included_com_istyle_document_convert_SPDocumentConvert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_istyle_document_convert_SPDocumentConvert
 * Method:    nativeInitialize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_istyle_document_convert_SPDocumentConvert_nativeInitialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_istyle_document_convert_SPDocumentConvert
 * Method:    nativeFinalize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_istyle_document_convert_SPDocumentConvert_nativeFinalize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_istyle_document_convert_SPDocumentConvert
 * Method:    nativeWordToPDF
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_istyle_document_convert_SPDocumentConvert_nativeWordToPDF
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
