server:
  port: 8456
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJFajyuGJnjW5/CEXGWPDqVvjTQrLpWYcH4hM/ukX1EG9P0l2TlMZGSlbtx8ww2ZYZayiv0bZFw6dl0z5P8n1ZUCAwEAAQ==

spring:
  application:
    name: word2pdf-core
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/word2pdf?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: b+6gSy972dWnal9P1C/sl4ncnnXKYXIfwTjQLUWGleXvY3pGbApZkcNRoWfKE1oo+Uu+g3zabF+QnIl0m9rYbg==
      #连接池配置
      #配置初始化大小、最小、最大、等待超时的时间
      initial-size: 5
      max-active: 20
      min-idle: 1
      max-wait: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      # 连接有效性验证
      validation-query: select 1 from dual
      # 针对oracle数据库，缓存pscache,并设置连接数
      max-pool-prepared-statement-per-connection-size: 100
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filter:
        config:
          enabled: true
        stat:
          enabled: true
        slf4j:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      # 监控配置
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # 数据库监控,默认上下文位置为/druid
      stat-view-servlet:
        enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS

mybatis:
  mapper-locations: classpath:mapper/*.sqlmap.xml
pagehelper:
  autoRuntimeDialect: true
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
path:
  nas: "D:/NAS"
  wordToPdfLocalPath-xin: D:/xpt/word2pdf/
cxf:
  path: /isignweb/services